swipe_nav:
  wrap: true
  animate: flip
  prevent_default: true
  swipe_amount: 15

title: Mobile
background: var(--background-image)
views:
  - !include lovelace/main.yaml
  - !include lovelace/home.yaml
  - !include lovelace/battery_level.yaml
  - !include lovelace/living_room.yaml
  - !include lovelace/hallway.yaml
  - !include lovelace/laundry.yaml
  - !include lovelace/bedroom.yaml
  - !include lovelace/guest_bathroom.yaml
  - !include lovelace/master_bathroom.yaml
  - !include lovelace/media_players.yaml
