###############################################################################
#   @author         :   Chris Smith
#   @date           :   10/02/2022
#   @package        :   Switchbot
#   @description    :   All the Switchbot related stuff. 
###############################################################################


rest_command:
  switchbot_device_command:
    url: 'https://api.switch-bot.com/v1.0/devices/{{ deviceId }}/commands'
    method: post
    content_type: 'application/json'
    headers:
      Authorization: !secret switchbot_api
    payload: '{"command": "{{ command }}","parameter": "{{ parameter }}"}'


sensor:
  - platform: rest
    name: 'Curtain Thing Position'
    resource: !secret curtain_thing_status_url
    method: GET
    scan_interval: 600
    headers:
      Authorization: !secret switchbot_api
      Content-Type: 'application/json'
    value_template: '{{ value_json.body.slidePosition }}'
    json_attributes_path: "$.body"
    json_attributes:
      - deviceId
      - deviceType
      - hubDeviceId
      - calibrate
      - group
      - moving
      - slidePosition


cover:
  - platform: template
    covers:
      curtain_thing:
        device_class: curtain
        friendly_name: "Curtain Thing"
        position_template: "{{ states('sensor.curtain_thing_position') }}"
        open_cover:
          service: rest_command.switchbot_device_command
          data:
            deviceId: !secret curtain_thing_deviceId
            command: "turnOn"
        close_cover:
          service: rest_command.switchbot_device_command
          data:
            deviceId: !secret curtain_thing_deviceId
            command: "turnOff"
        stop_cover:
          service: rest_command.switchbot_device_command
          data:
            deviceId: !secret curtain_thing_deviceId
            command: "turnOff"
        set_cover_position:
          service: rest_command.switchbot_device_command
          data:
            deviceId: !secret curtain_thing_deviceId
            command: "setPosition"
            parameter: "0,ff,{{position}}"